export const ActionTypes = {
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',
  FETCH_MOVIES_LOADING: 'FETCH_MOVIES_LOADING',

  FETCH_TRENDING_MOVIES_SUCCESS: 'FETCH_TRENDING_MOVIES_SUCCESS',
  FETCH_TRENDING_MOVIES_FAILURE: 'FETCH_TRENDING_MOVIES_FAILURE',
  FETCH_TRENDING_MOVIES_LOADING: 'FETCH_TRENDING_MOVIES_LOADING',

  FETCH_POPULAR_MOVIES_SUCCESS: 'FETCH_POPULAR_MOVIES_SUCCESS',
  FETCH_POPULAR_MOVIES_FAILURE: 'FETCH_POPULAR_MOVIES_FAILURE',
  FETCH_POPULAR_MOVIES_LOADING: 'FETCH_POPULAR_MOVIES_LOADING',

  FETCH_POPULAR_TVSHOWS_SUCCESS: 'FETCH_POPULAR_TVSHOWS_SUCCESS',
  FETCH_POPULAR_TVSHOWS_FAILURE: 'FETCH_POPULAR_TVSHOWS_FAILURE',
  FETCH_POPULAR_TVSHOWS_LOADING: 'FETCH_POPULAR_TVSHOWS_LOADING',

  FETCH_MOVIE_GENRES_SUCCESS: 'FETCH_MOVIE_GENRES_SUCCESS',
  FETCH_MOVIE_GENRES_FAILURE: 'FETCH_MOVIE_GENRES_FAILURE',
  FETCH_MOVIE_GENRES_LOADING: 'FETCH_MOVIE_GENRES_LOADING',

  FETCH_TVSHOW_GENRES_SUCCESS: 'FETCH_TVSHOW_GENRES_SUCCESS',
  FETCH_TVSHOW_GENRES_FAILURE: 'FETCH_TVSHOW_GENRES_FAILURE',
  FETCH_TVSHOW_GENRES_LOADING: 'FETCH_TVSHOW_GENRES_LOADING',
};
